repos:
  # All pre-commit hooks from `pre-commit-hooks`.
  # All removed hooks have a reason explaining why
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      # No AWS credentials in this (base) project
      #- id: detect-aws-credentials
      - id: detect-private-key
      # Interferes with ruff which requires double string usage
      #- id: double-quote-string-fixer
      - id: end-of-file-fixer
      # So far not applicable to this project
      #- id: file-contents-sorter
      - id: fix-byte-order-marker
      # Overrules by forbid-submodules
      #- id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--django']
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: ['--no-sort-keys']
      - id: requirements-txt-fixer
      # So far not applicable to this project
      #- id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/PyCQA/bandit
    rev: '1.9.4'
    hooks:
      - id: bandit
        args: ["-c", "backend/pyproject.toml"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.19
    hooks:
      - id: uv-lock
        files: backend/pyproject.toml
        args: [--project, backend]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
