[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Frans de Boer", email = "github.wife581@passmail.net" }
]
requires-python = ">=3.14"
dependencies = [
    "django==6.1.2",
    "django-environ==0.14.0",
]

[dependency-groups]
dev = [
    "bandit==1.9.4",
    "django-stubs-ext==6.1.1",
    "django-stubs[compatible-mypy]==6.1.1",
    "mypy==2.3.1",
    "pre-commit==4.6.2",
    "pytest==9.1.1",
    "pytest-django[django]==4.14.0",
    "ruff==0.16.8",
]
security = [
    "pip-audit==2.10.1",
]

[tool.uv]
exclude-newer = "1 week"

[tool.ruff.lint]
extend-select = [
    "ALL"
]

ignore = [
    "COM812", # missing-trailing-comma (incompatible with formatter)
    "CPY001", # Missing copyright notice at top of file
    "D100",   # Missing docstring in public modules
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method
    "D103",   # Missing docstring in public function
    "D104",   # Missing docstring in public package
    "D105",   # Missing docstring in magic method
    "D106",   # Missing docstring in public nested class
    "D203",   # incorrect-blank-line-before-class (incompatible with D211: blank-line-before-class)
    "D213",   # multi-line-summary-second-line (incompatible with D212: multi-line-summary-first-line)
]

[tool.ruff.lint.extend-per-file-ignores]
"tests*.py" = [
    "S101",   # Use of `assert` detected
    "S106",   # Possible hardcoded assignment to argument: "password"
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
strict = true

[[tool.mypy.overrides]]
module = ["environ.*"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "core.settings"
strict_settings = true
strict_model_abstract_attrs = true

[tool.bandit]
exclude_dirs = ["tests"]
tests = [
    "B101",  # assert_used
    "B106",  # hardcoded_password_funcarg
]

[tool.pytest]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
